apiVersion: v1
kind: Service
metadata:
  name: intesa-fx-platform-ui-client
  namespace: fx-tool
spec:
  selector:
    app: intesa-fx-platform-ui-client
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 80
  type: ClusterIP
