apiVersion: v1
kind: Service
metadata:
  name: intesa-fx-platform-ui-admin
  namespace: fx-tool
spec:
  selector:
    app: intesa-fx-platform-ui-admin
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP
