apiVersion: v1
kind: Service
metadata:
  name: intesa-fx-sqlserver
  namespace: fx-tool
spec:
  selector:
    app: intesa-fx-sqlserver
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
